Feat/auth 로그인
f-lab-edu/ticket-hub pull request #4
Opened 2024-03-18 09:53 UTC by jaeyeopme

## Issue

- #3

## Feature

- 로그인
    - 이메일 및 패스워드 검증
    - 엑세스 토큰 및 리프레시 토큰 반환
    - 리프레시 토큰 저장

## ETC

- Spring Security 기본 설정
- #2 비밀번호 암호화 로직 추가
- 테스트에서 AutoConfigure ObjectMapper 만 의존받고 싶은데 @JsonTest 가 최선인지는 잘 모르겠네요

2024-03-18 10:35 UTC, wheejuni requested changes
꼼꼼한 테스트까지 너무 좋습니다 👍 
하나만 더 시도해 보시면 좋을 것 같은데 코멘트 확인 부탁드립니다

2024-03-18 10:35 UTC, wheejuni commented on build.gradle.kts
> +    testImplementation("org.springframework.security:spring-security-test")
오 이거 있는줄 몰랐습니다;;

2024-03-18 10:35 UTC, wheejuni commented on src/main/kotlin/flab/tickethub/auth/adaptor/in/AuthCommandUseCase.kt
> +    fun updateRefreshToken(memberId: Long, refreshToken: String)
리턴 타입이 없어도 될까요? 뭔가 새로운 토큰을 줘야하는 구조는 아닌가보네요?

2024-03-18 10:35 UTC, wheejuni commented on src/main/kotlin/flab/tickethub/auth/application/service/AuthQueryService.kt
> +            throw ApiException(ErrorCode.INVALID_EMAIL_OR_PASSWORD)
오 보안까지 고려해서, PW/EMAIL중 뭐가 틀렸는지 안 알려주는 것 좋습니다. 👍

2024-03-18 10:35 UTC, wheejuni commented on src/main/kotlin/flab/tickethub/auth/application/service/AuthQueryService.kt
> +        return TokenPayload(member.id!!)
Kotiln nullable을 다룰 때 어지간해서는 `!!` 사용은 금지해 주시면 좋겠습니다.
물론 요 상황에서 ID가 있을거란 확신이 있다는 점엔 저도 공감은 합니다만, 그래도 100%는 아닌 거니까요(적어도 syntax 상으로는)

null check 후 null일 시엔 적절한 예외가 던져져야 되지 않나 생각해봅니다.

2024-03-18 10:35 UTC, wheejuni commented on src/main/kotlin/flab/tickethub/auth/application/service/JwtProvider.kt
> +    @Value("\${jwt.access.exp}") private val refreshExp: Long,
요거 `@ConfigurationProperties` 으로 개선 부탁드립니다!

2024-03-18 10:47 UTC, jaeyeopme commented on src/main/kotlin/flab/tickethub/auth/adaptor/in/AuthCommandUseCase.kt
> +    fun updateRefreshToken(memberId: Long, refreshToken: String)
프레젠테이션 레이어에서 토큰 발급 로직과 리프레시 토큰 업데이트 로직을 분리했습니다.

2024-03-18 10:48 UTC, jaeyeopme commented on src/main/kotlin/flab/tickethub/auth/application/service/AuthQueryService.kt
> +        return TokenPayload(member.id!!)
없는 문법이라 생각하겠습니다 ㅎㅎ

2024-03-18 11:35 UTC, jaeyeopme commented on src/main/kotlin/flab/tickethub/auth/application/service/JwtProvider.kt
> +    @Value("\${jwt.access.exp}") private val refreshExp: Long,
개선 피드백 반영했습니다.

2024-03-20 07:08 UTC, jaeyeopme commented
피드백 반영 이후 머지하겠습니다.

- JWT 프로퍼티 @ConfigurationProperties 개선
- Validation 정규식 및 메시지 상수 정의 개선
- Clock 빈에서 더 유연한 시간 타입 반환으로 구조 개선

2024-03-20 07:13 UTC, merged